services:
  # MongoDB Database
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - autodocs-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - autodocs-network

  # Ollama
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 4G
    entrypoint: [ "/bin/bash", "-c" ]
    command: |
      "ollama serve &
      sleep 10
      ollama pull nomic-embed-text
      wait"
    networks:
      - autodocs-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP protocol port (used by Celery or other workers)
      - "15672:15672" # RabbitMQ Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - autodocs-network
  # autodocs-backend:
  #   build:
  #     context: ./back-end
  #     dockerfile: Dockerfile
  #   container_name: autodocs-backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./back-end/src:/app
  #   environment:
  #     - PYTHONPATH=/app
  #     - PYTHONUNBUFFERED=1
  #   env_file:
  #     - ./back-end/.env
  #   working_dir: /app
  #   command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  #   networks:
  #     - autodocs-network

networks:
  autodocs-network:
    driver: bridge

volumes:
  ollama_data:
  mongo_data:
