[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.vscode
    | _build
    | buck-out
    | build
    | dist
)/
'''
[tool.mypy]
disable_error_code = ["import-untyped"]
