version: '3.8'

services:
  # Ollama
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 4G
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "ollama serve &
      sleep 10
      echo 'Đang tải model nomic-embed-text...'
      ollama pull nomic-embed-text
      echo 'Đang tải model qwen3:1.7b...'
      ollama pull qwen3:1.7b
      echo 'Hoàn thành tải models!'
      wait"

volumes:
  ollama_data:

